version: '3'

services:

  #Nginx Service
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - php
      - mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - laravel

  #PHP Service
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  #MYSQL Service
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - laravel

#Docker Networks
networks:
  laravel:
    driver: bridge
